[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Master-Hash", email = "hash@hash.memorial"},
]
dependencies = [
    "textual>=0.44.1",
    "requests>=2.31.0",
    "deep-translator>=1.11.4",
]
requires-python = ">=3.12"
readme = "README.md"
license = {text = "MIT"}

